amanjaiman1/Product_3D

README.md

Contributor graph update

---

README.md

Back to top button added

---

client/package-lock.json
client/package.json
client/src/index.css
client/src/pages/Customizer.jsx

Closes #4 
I have added Neumorphism to the tabs respectively
On opening a particular filter a closing button appears which can be used to close the filter on the Editor Tab

Closing Function and Neumorphism added

---

CONTRIBUTING.md

@amanjaiman1 I have added the CONTRIBUTING.md file.
Please review it.

Added Contributing Guidelines file type markdown.

---

client/src/index.css

Issue Solved #62 
Now you can show the Editor Content component close icon button in dark mode.
Light mode
Dark mode

UI Improvement

---

server/example.env
server/index.js
server/package-lock.json
server/package.json
server/routes/dalle.routes.js

add unsplash and pexels api for image generations and all testing done from my side on local system its works good without any bug or error.

add some more image generators api's

---

client/index.html
client/src/index.css
client/src/pages/Customizer.jsx
client/src/pages/Home.jsx

Updated the nav bar and fixed the go back buttons.
PS: I think the nav bar can stay through all the pages since it increases navigational benefits for the user.

Updated Nav Bar 

---

.github/dependabot.yaml

Fixes #72 
pls review @amanjaiman1

Depandabot added

---

client/package-lock.json
client/package.json
client/src/components/AIPicker.jsx
client/vite.config.js

if any case its voice feature not working just type in a keyboard to start listening feature

Added Speech to text

---

.github/workflows/close_old_issues.yaml

close old issues action added

---

package.json
server/config/unsplash.config.js
server/package-lock.json
server/package.json

I would like to work under GSSOC'23

fix: fetch is not defined in unplash api

---

client/package-lock.json
client/package.json
client/src/components/Navbar.jsx
client/src/components/navbar.css
server/server.js

i have enhanced the navbar exactly like told. I have only changed the UI and not touched the links and router part although some links in navbar dont lead anywhere. 
Before:
After:
Hope you like my work.

Enhanced Navbar according to the photo provided

---

client/src/components/Navbar.jsx
client/src/components/navbar.css

happy to contribute in this project :)

issue #146

---

client/src/components/ContributorCard/index.jsx
client/src/components/Pagination/index.jsx
client/src/containers/Contributors/index.jsx
client/src/containers/Hero/index.jsx
client/src/index.css
client/tailwind.config.js

Balaji sivasakthi/fix team section

---

client/package-lock.json
client/src/containers/Header/Navbar.css
client/src/containers/Header/Navbar.jsx
client/src/views/app/Error.jsx

Navbar fixed & Error Page Added

---

client/src/App.jsx
client/src/pages/Accordion.jsx
client/src/pages/AccordionItem.jsx
client/src/pages/Faq.jsx
client/src/scss/_animation.scss
client/src/scss/_attribution.scss
client/src/scss/_component.scss
client/src/scss/_config.scss
client/src/scss/_faq.scss
client/src/scss/_illustration.scss
client/src/scss/_responsive.scss
client/src/scss/main.scss
client/src/views/app/Faq.jsx

Fixed the navbar bug in Faq page

---

client/src/App.jsx
client/src/views/auth/Login.jsx
client/src/views/auth/SignUp.jsx

-Added the login page and signup page
-set the routes for both

Added the login and signup pages

---

client/src/pages/Faq/Faq.jsx
client/src/pages/Faq/faq.css

@amanjaiman1  bro issue #175 pleased assigned the label gssoc before the merge

Added Questions

---

client/package-lock.json
client/src/containers/Header/Navbar.jsx
client/src/index.css

resolved the navbar issues

---

client/index.html
client/src/index.css

Customized scrollbar at the global index.css file rather than doing it directly in the index.html file like you said. This time even added hover effect.

Changes in the scrollbar

---

README.md

Closes #165 
I have appended a contributor graph to the README.md file.

docs: Add Contributor Graph

---

client/vercel.json

added vercel.json for routes issue
#218

chore:added vercel.json

---

client/src/App.jsx
client/src/components/Button/index.jsx
client/src/redux/user/index.js
client/src/store/index.js
client/src/test/user.test.jsx

#29 
@JTtime @amanjaiman1 
I've completed the redux state management for user. 
> Additionally, I created a component for testing the state by using updateUser Reducer and  dispatch it in test/user.test.js 
`GET /test`
----------------------------
----------------------------

[Feat]: State Management for User

---

client/src/containers/Footer/index.jsx

Better compatibility for Mobile Devices.

Enhanced Footer #2

---

client/src/containers/TeamPost/CardData.jsx
client/src/containers/TeamPost/TeamPostCard.jsx

Added the card data file for the testimonials section #179 
Now @amanjaiman1 you can merge this and please close #179 
And please also add labels to the pr 
Thanks and I would love to contribute more to this repo 😄

added cardData - 007aneesh

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/index.css

Frontend:added ScrollToTop issue-138

---

client/index.html
client/package-lock.json

This pull request adds a description about meta tags to the documentation. Meta tags are small snippets of text that provide information about a web page to search engines and other web services. They are typically included in the head section of an HTML document.
Changes
-     A new section has been added to the documentation titled "Primary Meta Tags."

Meta tags added

---

client/src/containers/Footer/index.jsx

Closes #255 
Added a unique key prop to the map function which removed the error message from the browser console.

Added unique key prop

---

client/src/pages/Faq/AccordionItem.jsx

FAQ questions were not toggling properly. It wasn't toggling out or closing back on click hence changed the toggle out on click once it is viewed.
Screenshot: 
Now on clicking it it closes and toggles properly, every question. 
Issue: #252 
Closes: #252

Updated FAQ

---

client/src/components/FeatureCard/index.jsx
client/src/components/FeatureCard/style.css

Added flip effect in cards.
Preview:
https://github.com/amanjaiman1/Product_3D/assets/105661636/81a8cf4b-8e49-4d21-8b48-d16f0d0a47f6

Enhanced feature cards

---

client/src/pages/Guidebook/guidebook.jsx

Added margin at the beginning of the guide book page.

Added margin  on top for guidebook page

---

client/src/index.css
client/src/pages/Guidebook/guidebook.jsx

fixed issue #270 

---

client/old/components/Contact.jsx
client/src/components/ContributorCard/index.jsx
client/src/components/FeatureCard/index.jsx
client/src/containers/Hero/index.jsx
client/src/containers/TeamPost/TeamPostCard.jsx
client/src/pages/Contact/Contact.jsx

Added alt attributes to all the img tags where it was missing.

Alt attributes added to img tags

---

CONTRIBUTING.md

updated Contributing.md

---

client/src/containers/TeamPost/index.jsx

Fixes #269
I have changed this sentence:
> Go Through Reviews Of Previews Students To Make An Informed Decision
to:
> Go Through Reviews Of Our Previous Clients To Make An Informed Decision
This PR is part of GSSoC'23.

Fix Text in Landing Page

---

client/package-lock.json
client/package.json
client/src/views/auth/Login.jsx
client/vite.config.js

Issue Fixed 
@amanjaiman1  assigned me under gssoc before merged Issue #280

[Fix]: Firebase auth at web and mobile view

---

client/src/App.jsx
client/src/containers/Footer/index.js
client/src/containers/Footer/index.jsx
client/src/utils/AutoScroll.jsx

Added navlink to make the footer links to navigate to their corresponding page. For links does not exist, replaced those links with the home route ("/") so that in the future when the links are updated then no need to make any changes in the footer code.

Footer links made functional

---

client/src/containers/Footer/index.jsx

A blue line was introduced in the home and blog pages due to using Navlink in the footer. Removed the line by using Link instead of Navlink in the footer.

[BUG] Blue line removed from pages

---

client/src/components/ContributorCard/index.jsx
client/src/containers/Hero/homeUI.css
client/src/containers/Hero/index.jsx
client/src/layout/HomeLayout.jsx

Added some responsiveness to main page, properly aligned contributor cards.
Raised under issue number **#303** 
Main hero component preview
Contributor card  alignment preview
Hey @amanjaiman1 please review this one.

Responsive and proper alignment of Homepage

---

DESIGN.md
newsletter_link.txt

Blueprint design of newsletter

newletter_design

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Added checkboxes in issues template

---

.github/ISSUE_TEMPLATE/workflows/close_old_issues.yaml

close old issue bot add
this pr will close #320

#320 Bot added

---

client/src/containers/TeamPost/TeamPostCard.jsx

Closes Issue No: <#312>
- **Update Controllable Swipers Speed in Testimonial Section.**

Controlled Swipers Speed in Testimonial Section

---

.github/pull_request_template.md

* Closes #335 
Added the PR template with different sections such as Issue No, Description, Screenshots, Checklists, etc.

Added the Pull Request template

---

client/src/components/CustomizerOptions/index.jsx
client/src/components/CustomizerViewer/CameraRig.jsx
client/src/components/CustomizerViewer/Shirt.jsx
client/src/components/CustomizerViewer/ShirtDrag.jsx
client/src/components/CustomizerViewer/index.jsx
client/src/components/CustomizerViewer/valito.js

Related Issue:
Closes: #59
Describe the changes you've made:
I have made the following modifications:
- Fixed the rotation bug in the customizer page.
- Added functionality to enable rotation only on mouse cllick / grab(functionality).
- Adjusted the aspect ratio of rotation.
Type of change:
How Has This Been Tested?
I have tested the changes to ensure proper functionality.
Checklist:
Screenshots:
N/A
Code of Conduct:

added changes in customiser pages

---

README.md

*Added env setup steps* @amanjaiman1 
#357 
Closes: #357 
- [x ] Documentation update.
- [ x] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

Update README.md issue-357

---

README.md

Update README.md (added the discord link)

---

client/src/components/CustomizerColor/index.jsx

Closes: # 
Here's a breakdown of the code:
The component imports the necessary dependencies: React and useState from React, and state from ../CustomizerViewer/valito.
The CustomizerColor component is defined as a functional component.
An array called basicColors is declared, which contains a set of color values.
Several state variables are initialized using the useState hook: selectedColor, selectedColorIndex.
Two event handler functions are defined: handleColorChange and handleBasicColorClick. These functions update the state variables based on user interactions.
The component's return statement contains the JSX code that represents the color picker interface.
It consists of a div element enclosing the color picker elements.
Inside the div, there is …

Added color page

---

client/public/sitemap.xml

- I have added the sitemap to this project which results in improved SEO.
Closes: #382 
I have added the stemap.xml file in the public folder of the client section. search engines like Google and Bing crawl this sitemap

Added sitemap

---

client/src/assets/index.js
client/src/views/auth/Login.jsx
client/src/views/auth/SignUp.jsx

issue #383 
Re-designed Login and SignUp page for our website 
Here is the preview
https://www.loom.com/share/c60965dd3d4f4bc684168c901ae79b81?sid=00157f57-e7e9-4523-8816-6da15df8b04d
https://www.loom.com/share/56abf967ea5d423290668675f4c96d01?sid=a0dc57d0-40ac-4eac-bac8-03a12a8dc739

feat(login): added login and Signup page

---

client/src/components/CustomizerViewer/Shirt.jsx
client/src/components/CustomizerViewer/index.jsx
client/src/redux/customizer-load/index.js
client/src/store/index.js

refactor(customizer): isLoading state in redux

---

client/src/components/CustomizerTopbar/index.jsx

- Customizer top bar was not fixed earlier
Closes: #401
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the guidelines of this project.
- [x ] My changes generate no new warnings.
https://github.com/amanjaiman1/Product_3D/assets/101205226/dd72c3cf-a5c9-46cb-a01e-6371135ed61b
- [x ] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

Fixed the Customizer topbar

---

client/src/App.jsx
client/src/components/Avatar/index.jsx
client/src/components/CustomizerSidebar/index.jsx
client/src/components/CustomizerTopbar/index.jsx
client/src/components/FormGroup/index.jsx
client/src/components/TextField/index.jsx
client/src/containers/ProfileContainer/index.jsx
client/src/views/app/Profile/index.jsx

added  #398 
- added new component form group
- added profile page
- added few inputs like email, username, mobile and job.

feature: profile page for users

---

client/src/components/CustomizerColor/index.jsx
client/src/components/CustomizerNavBar/index.jsx
client/src/components/CustomizerSettings/index.jsx
client/src/layout/EditorLayout.jsx

responsive addition to Customizer Page

---

client/src/components/CustomizerTopbar/index.jsx
client/src/views/auth/Login.jsx

_Optimization of Login Component
The Login component has been improved to support Google sign-ins. Additionally, it now stores user data in a secure place known as 'localStorage'. This data storage upgrade ensures that user information is saved locally for a better, faster and more seamless user experience.
Conditional Rendering of Google Sign-In Button
A new feature has been added to the Login component, which controls the display of the Google sign-in button based on specific conditions. This logic greatly improves the user interface usability._
Closed #423 
https://github.com/amanjaiman1/Product_3D/assets/72148636/1938e2b3-d1fb-42eb-a0b6-959a9d462418

added the google auth

---

client/src/components/CustomizerSidebar/index.jsx
client/src/containers/RecentDesigns/index.jsx

Closes: #406
- Aligned the customizer cards initially they are left aligned
- Corrected cards 1 text
- Fixed the overflow of sidebar
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Code style update (formatting, local variables)
- [ x] I have performed a self-review of my own code.
- [ x] My changes generate no new warnings.
- [x ] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

Cards alignment  and sidebar of customizer fixed

---

client/src/components/CustomizerSidebar/index.jsx
client/src/containers/RecentDesigns/index.jsx

Reverts amanjaiman1/Product_3D#425

Revert "Cards alignment  and sidebar of customizer fixed"

---

client/src/pages/Contact/Contact.css
client/src/pages/Contact/Contact.jsx

added the new design

---

.github/workflows/auto-commit.yml

Closes: #227
To run This workflow you have to Give some Permission  : 
Yes

feat:  Created Auto-commit Workflow. ✔

---

client/src/components/CustomizerViewer/index.jsx

Fixes issue #440 
I fixed the 3d model for the desktop view.
But when I tested it for responsiveness the containers has some issues and it overflows. I was not able to fix that as I did not find the relevant code.
But everything is fine in desktop mode.
@amanjaiman1 Please review it and merge with the main branch.

Fixed position of 3d model

---

.github/workflows/JSON.yml

#444
Created Workflow  .github/workflows/json-check.yml 

feat:  JSON.yml created. ✔

---

client/src/containers/Header/Navbar.jsx

Solved #issue 460
Re-Designed the Navbar as per the description given in the issue

feat(navbar): Re-Designed Navbar

---

client/package-lock.json
client/package.json
client/src/components/Avatar/index.jsx
client/src/components/CustomizerNavBar/index.jsx
client/src/components/CustomizerTopbar/index.jsx
client/src/components/FormGroup/index.jsx
client/src/components/PopupModel/index.jsx
client/src/components/TextField/index.jsx
client/src/containers/ProfileContainer/index.jsx
client/src/containers/ProfileEditor/index.jsx

feat #417 
- Created new popup model
- Updated style for **TextField** component width as 100%
- Created profile editor container
- Installed new dependency **formik**
- Updated style for avatar component

[Feature]: Added Edit Profile with popup model

---

client/src/pages/Guidebook/guidebook.jsx

- Guide page is not aligned properly
- The spin element in guide page is overflowing in big screen size 
- The hero image in guide page is also stretching for big screen
Closes: #428
- I properly aligned the guide page
- Also made it responsive for different screen sizes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the guidelines of this project.
- [x ] My changes generate no new warnings.
https://github.com/amanjaiman1/Product_3D/assets/101205226/45cbc2cd-8238-4faf-a19e-b9ad0d145157
- [ x] I agree to follow this project's [Code of …

Proper alignment of Guide Page

---

client/src/pages/Faq/Faq.jsx

Closes: #451 
I have added a space between 'styles' & 'and'.
This PR is part of GSSoC'23.

Fix text in FAQ page

---

client/src/containers/TeamPost/TeamPostCard.jsx

Closes: #456 
- Made Testimonials accessible by using `figure`, `figcaption` and `blockquote`.
- Tested with NVDA Screen Reader
- We can't take screenshots of accessibility changes rather than code changes, Accessibility changes are often invisible to the user because it's intended to guide disabled people

feat: make testimonials accessible ✨

---

src/views/auth/SignUp.jsx

Closes: #503 
Fixed the code conflict in signup page

fix(signup): fixed code in signup page

---

CONTRIBUTING.md
README.md

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Code style update (formatting, local variables)
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [x ] I have added tests that prove my fix is effective or that my feature works.
- [x ] Any dependent changes have been merged and published in downstream modules.
- [x ] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

docs(readme): update the readme file and remove extra contents

---

src/components/CustomizerColor/index.jsx
src/components/CustomizerDesign/index.jsx
src/components/CustomizerLogo/index.jsx
src/components/CustomizerOptions/index.jsx
src/components/CustomizerSettings/index.jsx
src/components/CustomizerTabs/index.jsx
src/components/CustomizerText/index.jsx
src/containers/Customizer/index.jsx
src/index.css
src/layout/EditorLayout.jsx

refactor #515 
- refactored customizer editor layout
- renamed labels like customizer text into text & image
- refactor buttons in few places
- refactor layouts in customizer tabs

refactor: customizer editor layout and customizer tabs

---

package.json
src/App.jsx
src/components/CustomizerTitle/index.jsx
src/containers/Customizer/index.jsx

feat: #517 
- added new component customizer title
- go back to functionality in the customizer page
- updated routes for editor page using params

feat: customizer title and go back functionality

---

src/components/CustomizerNavBar/index.jsx
src/components/CustomizerTopbar/index.jsx
src/components/DialogBox/index.jsx
src/components/RecentDesignCard/index.jsx
src/containers/RecentDesigns/index.jsx

feat  #469 
- added dialogue box component
-  store the t-shirt design in Firebase by uuid
- consume firebase data 
- removed a few harder code
- refactor old code

feat: Store recent design using firebase

---

src/containers/ProfileContainer/index.jsx
src/containers/ProfileEditor/index.jsx

refactor: #523 
- implemented functionality user profile update
- setup Firebase functionality in the profile editor

refactor: profile update functionality with firebase

---

src/App.jsx
src/components/ContextMenu/index.jsx
src/components/CustomizerSidebar/index.jsx
src/components/DialogBox/index.jsx
src/components/RecentDesignCard/index.jsx
src/containers/Favourite/index.jsx
src/containers/RecentDesigns/index.jsx
src/views/app/Favourite/index.jsx

feat #520 
- added context menu component
- implemented needed event handler
- fix sidebar issue
- implemented remove functionality
- implemented open new tab design

feat: customizer context menu

---

src/pages/Guidebook/guidebook.jsx

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the guidelines of this project.
- [ x] I have commented on my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [x ] I have added tests that prove my fix is effective or that my feature works.
- [x ] Any dependent changes have been merged and published in downstream modules.
https://github.com/amanjaiman1/Product_3D/assets/101205226/fea3e4da-ce8f-4aec-8487-d6b65187e5ac
https://github.com/amanjaiman1/Product_3D/assets/101205226/4ff42a91-cd56-404b-aeb8-0ab46e5a106f
- [ x] I agree to follow this project's [Code …

fix(guidebookcards): made card responsvie

---

README.md

Closes: #528 
Added the MIT License badge and some text to Licenses section

Added the MIT License badge and some text to Licenses section

---

admin/index.js
admin/package-lock.json
admin/package.json
admin/routes/mail.js
admin/routes/newsletter.ejs
admin/routes/verify.js
src/containers/NewsLetter/index.jsx
src/pages/Contact/Contact.css
src/pages/Contact/Contact.jsx
src/utils/PrivateRoute.jsx
src/views/auth/Login.jsx

#526 
- installed `nodemailer` and  `ejs`
- backend api for sending email to the subscriber
- implemented news letter functionality in client
- created mail templated

feat: new letter implementation

---

src/components/BlogCard/bcard.jsx
src/pages/Blog/Blog.jsx

Closes: #533
I've changed the UI and made the page responsive. 

Changing Blog UI

---

src/containers/Footer/index.jsx
src/containers/Hero/homeUI.css
src/containers/Hero/index.jsx
src/pages/Contact/Contact.css
src/pages/Contact/Contact.jsx

Improving the components of heroUI, Footer and contributor card,
Closes: #514
- Make changes in CSS files named heroUI.css and Contect.css
- Updated the behavior of heroUI with screen changes
- In contribution card aligned the content at the center and changed the background color to blue-gradient.  
The changes has tested for different screen like PC, Tab, mobile.

feat: improve heroUI, footer-button and contribution-card in contact section

---

src/containers/Footer/index.jsx
src/containers/Hero/homeUI.css
src/containers/Hero/index.jsx
src/pages/Contact/Contact.css
src/pages/Contact/Contact.jsx

Reverts amanjaiman1/Product_3D#535

Revert "feat: improve heroUI, footer-button and contribution-card in contact section"

---

README.md

- Fixes broken link in the README.md
Closes: #532 
- I updated the README.md to fix a broken link to the Discord server.
I have verified the changes by following the link in updated README.md and confirming that the Discord link now works as expected.
N/A

docs: correct discord link in README.md

---

package-lock.json
package.json
src/components/ContextMenu/index.jsx
src/components/CustomizerTopbar/index.jsx
src/utils/utils.js

#530 
- Installed `file-saver` lib
- add utils `serializeToP3D `& `deserializeFromP3D`
- handle the functionality of export and import
- stored the imported data in firebase

feat: import and export design

---

src/App.jsx
src/components/FAQCard/faqCard.jsx
src/index.css
src/layout/HomeLayout.jsx
src/pages/Blog/Blog.jsx
src/pages/Faq/Faq.jsx
src/pages/Guidebook/guidebook.jsx
src/store/faqData.js

Closes: #547
I've changed the scrollbar, the FAQ data and some minor font changes.

Changing scrollbar and FAQ page data

---

src/pages/Contact/Contact.css
src/pages/Contact/Contact.jsx

- Created all new template of contributor cards
- Applied the gradient colors for front and back of the cards
- Added animation
- Also the heading "Meet Our Talented Team" is not visible
- Aligned the back content of the cards
- Added github gradient icon
-  Pagination numbers not visible earlier
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Code style update (formatting, local variables)
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no …

fix: created whole new template of cards and animation

---

src/App.jsx
src/containers/Footer/index.js
src/containers/Footer/index.jsx
src/containers/Hero/index.jsx

Closes issue #551 
Added Extra titles and links,
Changed the font-family,
Removed unnecessary buttons,
Fixed the hero container,

[FEAT]: footer Designed

---

src/App.jsx
src/components/CustomizerColor/index.jsx
src/components/CustomizerLogo/index.jsx
src/components/CustomizerSidebar/index.jsx
src/components/CustomizerText/index.jsx
src/components/CustomizerTopbar/index.jsx
src/containers/SettingsContainer/index.jsx
src/views/app/Settings/index.jsx

#563 
- fix the customizer button's primary colors
- feat added setting page in the customizer

feat: setting page for customizer

---

src/containers/Hero/index.jsx

Closes #552 
1. Added text fields
2. Applied gradient colors
3. Adjusted the hero section

[FEAT]: Designing the text area of hero section

---

src/layout/HomeLayout.jsx

Removed the margin and padding at the homelayout page
Closes: # 

Removed margin and padding at home layout.

---

src/containers/NewsLetter/index.jsx
src/views/app/Home/index.jsx

Reated Issue:- 
#577 
Changes Made:- 
- refracted news letter to out new theme

style: news letter fix

---

src/App.jsx
src/components/CommunityPreviewCard/index.jsx
src/components/ContextMenu/index.jsx
src/components/CustomizerSidebar/index.jsx
src/components/CustomizerTopbar/index.jsx
src/containers/Community/index.jsx
src/views/app/Community/index.jsx

#586 
- community page with a private route
- firebase implementation
- search functionality for community
- default fork option

feat: community in customizer page

---

src/components/BlogCard/bcard.jsx
src/pages/Blog/Blog.jsx
src/pages/Blog/CreatePost.jsx
src/pages/Blog/EditPost.jsx

Make a CURD operation of Post in Blog Page
Closes: #588 
- Add Card
- Add firebase Storage for image upload and set to downloadable url
- Add Firebase firestore
- fixed the routes
- Render html config data

feat: add Curd opertaion and card Functionality

---

src/components/BlogCard/bcard.jsx
src/pages/Blog/Blog.jsx
src/views/app/Home/index.jsx

Closes: #594 
- add the tags tabs
- fixed the card edit and delete button functionality in blog page
- add the edge vedio effect
- add search functionality in blog page on the basis of title and tags

feat: fixed design and search bar and  add tags

---

src/components/CommunityVideos/index.jsx
src/views/app/CommunityLanding/index.jsx

closes issue #606 
1. Designed the image card for each grid
2. Added Youtube video feature

feat(community): community video container

---

src/components/CommunityNews/index.jsx
src/components/CommunityVideos/index.jsx
src/views/app/CommunityLanding/index.jsx

Community video container #614 by senthil

---

src/components/ExploreCustomized/index.jsx
src/views/app/Explore/index.jsx

closes issue #626
1. Implemented the Our Design Work Container in Explore Page
2. Designed image for the container
3. Implemented as per UI/UX design.

feat(explore): Added Our Design work feature

---

src/components/ExploreWork/index.jsx
src/views/app/Explore/index.jsx

closes issue #627 
1. Implemented our work container
2. Designed as per the UI/UX Design
3. Designed image for each container

feat(explore): implemented our work feature

---

.github/ISSUE_TEMPLATE/styles.yml

- Information about the related issue No : #592 
Closes: #592 
- **Created styles.yml File in .github/ISSUE_TEMPLATES Section for Raising Enhancement and Code Style Related Issues**
- **Added Suitable YAML Code for styles.yml File**

feat: Added styles.yml File in ISSUE TEMPLATES List

---

src/containers/Footer/index.jsx
src/containers/HightLights/index.jsx
src/layout/HomeLayout.jsx

fix: footer design

---

src/containers/Header/Navbar.jsx
src/containers/Hero/index.jsx

fix: broken link

---

src/components/FeatureCard/index.jsx
src/containers/HightLights/index.jsx

fix: hightlight

---

src/components/ContributorCard/index.jsx

fix: contributor page text color

---

src/containers/NewsLetter/index.jsx

fix: newsletter color match

---

src/components/Helpfaq/index.jsx
src/components/Needhelp/index.jsx
src/containers/Footer/index.jsx
src/pages/About us/About.jsx
src/pages/Helpcenter/Helpcentre.jsx

Closes: #633 
Added Responsiveness in About us, and Help center page

Fixed Responsiveness

---

src/components/ContextMenu/index.jsx
src/components/CustomizerNavBar/index.jsx
src/components/CustomizerTopbar/index.jsx
src/containers/ProfileContainer/index.jsx
src/containers/SettingsContainer/index.jsx

fix: button style in customizer

---

src/containers/CommunityFunding/index.jsx
src/views/app/CommunityLanding/index.jsx

closes issue #657 
Implemented Funding program feature for our product
Designed image for our product

feat(community): implemented funding program

---

src/App.jsx
src/components/CustomizerSidebar/index.jsx
src/containers/TeamContainer/index.jsx
src/views/app/Teams/index.jsx

Feat: team design in customizer

---

src/containers/TeamContainer/index.jsx

feat: search functionality in teams

---

src/containers/PluginsContainer/index.jsx

feat: search functionality on customizer plugin

---

src/components/Button/index.jsx
src/components/CustomizerNavBar/index.jsx
src/components/CustomizerSettings/index.jsx
src/components/CustomizerSidebar/index.jsx
src/components/CustomizerTabs/index.jsx
src/components/CustomizerTitle/index.jsx
src/components/CustomizerToolTip/index.jsx
src/components/CustomizerTopbar/index.jsx
src/components/DialogBox/index.jsx
src/containers/Customizer/index.jsx
src/layout/EditorHomeLayout.jsx
src/layout/EditorLayout.jsx
src/pages/Blog/CreatePost.jsx

Closes: #562 
- Add the dark mode in customiser pages

feat: set dark theme in customiser page

---

src/components/CustomizerLogo/index.jsx

Closes: #678 
- Fixed fetch button
- Fixed forward button
- Fixed Prev Button
- fixed 3d model ui

feat: working of the next prev buttons in customiser page

---

src/pages/Blog/Blog.jsx

- I fixed the hero section of the blog page
- Make it responsive for different screen sizes
- Also fixed the subscribe button
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Code style update (formatting, local variables)
- [ x] I have performed a self-review of my own code.
- [x ] My changes generate no new warnings.
https://github.com/amanjaiman1/Product_3D/assets/101205226/adc8296b-708b-41ac-8032-a5e81753acb8
https://github.com/amanjaiman1/Product_3D/assets/101205226/1b47beda-3038-40e6-98de-2a6b3c1ac0f3
- [ x] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

fix: blog page

---

src/containers/CreateTeamContainer/index.jsx

feat: team create firebase

---

src/containers/ExploreEvent/index.jsx

fix: bug in explore event

---

src/components/FormGroup/index.jsx
src/components/PluginCard/index.jsx
src/components/PopupModel/index.jsx
src/components/RecentDesignCard/index.jsx
src/containers/Favourite/index.jsx
src/containers/ProfileEditor/index.jsx
src/containers/SettingsContainer/index.jsx
src/containers/TeamContainer/index.jsx

fix: dark style

---

src/containers/Header/Navbar.jsx

- Made the navbar sticky with blur effect 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have commented on my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [ x] I agree to follow this project's [Code of Conduct](https://github.com/amanjaiman1/Product_3D/blob/main/CODE_OF_CONDUCT.md)

style: sticky navbar
